# Generated by Django 3.2 on 2022-03-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_auto_20220328_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselbanner',
            name='interval',
            field=models.IntegerField(choices=[(5000, '5сек'), (10000, '10сек'), (30000, '30сек')], default=5000, verbose_name='Интервал'),
        ),
    ]
