# Generated by Django 3.2 on 2022-04-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_auto_20220404_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='conditions_en',
            field=models.TextField(null=True, verbose_name='Условия'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название кинотеатра'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название кинотеатра'),
        ),
        migrations.AddField(
            model_name='events',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='events',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название события'),
        ),
        migrations.AddField(
            model_name='halls',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание зала'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='text_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movies',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название фильма'),
        ),
        migrations.AddField(
            model_name='page',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
