# Generated by Django 3.2 on 2022-04-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20220404_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='conditions_en',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='events',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='events',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='halls',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='homepagebanner',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_en',
        ),
    ]
