# Generated by Django 3.2 on 2022-04-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_auto_20220404_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='seo_text_ru',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_text_uk',
            field=models.TextField(null=True, verbose_name=''),
        ),
    ]
