version: '3.7'

services:

  cinema:
    build: .
    container_name: container_cinema
    command: make start_app
    expose:
      - 8000
    volumes:
      - .:/app:rw
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: 'redis:alpine'

  celery:
    restart: always
    build: .
    command: make worker
    ports:
      - "587:587"
    env_file:
      - .env
    depends_on:
      - cinema
      - redis

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - cinema


volumes:
  postgres_data:
  static_volume:
  media_volume:
