version: '3.7'

services:

  cinema:
    build: .
    container_name: container_cinema
    command: >
      sh -c "make start_app"
    volumes:
      - .:/app:rw
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  redis:
    image: 'redis:alpine'

  celery:
    restart: always
    build: .
    command: >
      sh -c "make worker"
    ports:
      - "587:587"
    env_file:
      - .env
    depends_on:
      - cinema
      - redis

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - cinema


volumes:
  postgres_data:
  static_volume:
  media_volume:
